<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBlrzxmt\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBlrzxmt/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerBlrzxmt.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerBlrzxmt\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerBlrzxmt\appProdProjectContainer(array(
    'container.build_hash' => 'Blrzxmt',
    'container.build_id' => 'e81636b1',
    'container.build_time' => 1525814860,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerBlrzxmt');
