<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerY1cikb0\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY1cikb0/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerY1cikb0.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerY1cikb0\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerY1cikb0\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Y1cikb0',
    'container.build_id' => '9630a2af',
    'container.build_time' => 1525814582,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerY1cikb0');
