-- SEXO
create table SEXO (
	ID_SEXO INT primary key,
	NOMBRE VARCHAR(12) not null
)

-- PAIS
create table PAIS (
	ID_PAIS INT primary key,
	NOMBRE VARCHAR(100) not null,
	GENTILICIO VARCHAR(100)
)

-- TIPO DE DOCUMENTO DUI/PASAPORTE U OTRO
create table TIPO_DOCUMENTO (
	ID_TIPO_DOCUMENTO INT primary key,
	NOMBRE VARCHAR(50) not NULL
)

-- ZONA
create table ZONA (
	ID_ZONA INT primary key,
	NOMBRE VARCHAR(20) not null
)

-- DEPARTAMENTOS
create table DEPARTAMENTO (
	ID_DEPARTAMENTO INT primary key,
	ID_ZONA INT,
	NOMBRE VARCHAR(50) not null,
	constraint DEPARTAMENTO_ZONA_FK foreign key (ID_ZONA) references ZONA (ID_ZONA)
)

-- MUNICIPIOS
create table MUNICIPIO (
	ID_MUNICIPIO INT primary key,
	ID_DEPARTAMENTO INT,
	NOMBRE VARCHAR(100) not null,
	constraint MUNICIPIO_DEPARTAMENTO_FK foreign KEY(ID_DEPARTAMENTO) references DEPARTAMENTO(ID_DEPARTAMENTO)
)

-- CLIENTES
create table CLIENTE (
	ID_CLIENTE INT AUTO_INCREMENT primary key,
	ID_SEXO INT,
	ID_PAIS INT,
	ID_MUNICIPIO INT,
	ID_TIPO_DOCUMENTO INT,
	NOMBRES VARCHAR(30) not null,
	APELLIDOS VARCHAR(30) not null, 
	APELLIDO_CASADA VARCHAR(15),
	SEXO CHAR(1),
	FECHA_NACIMIENTO DATE,
	DIRECCION VARCHAR(200),
	DUI VARCHAR(10),
	NIT VARCHAR(17),
	TELEFONO VARCHAR(50),
	EMAIL VARCHAR(50),
	constraint CLIENTE_SEXO_FK foreign KEY(ID_SEXO) references SEXO(ID_SEXO),
	constraint CLIENTE_PAIS_FK foreign KEY(ID_PAIS) references PAIS(ID_PAIS),
	constraint CLIENTE_MUNICIPIO_FK foreign KEY(ID_MUNICIPIO) references MUNICIPIO(ID_MUNICIPIO),
	constraint CLIENTE_TIPO_DOCUMENTO_FK foreign KEY(ID_TIPO_DOCUMENTO) references TIPO_DOCUMENTO(ID_TIPO_DOCUMENTO)
)